fix: nightly install
Intalling nightly would fail because it's using local path (relative to
{subdir}) where a path relative to the root is expected:

lib.ce_install  INFO     compilers/c++/cross/gcc/arm64/nightly trunk
failed to install:
 During symlinking, /opt/compiler-explorer/gcc-trunk-20230113 was not
 present
Traceback (most recent call last):
...
RuntimeError: During symlinking, /opt/compiler-explorer/gcc-trunk-20230113 was not present

Tested by installing locally cross gcc for bpf and arm64, and hook.

Signed-off-by: Marc Poulhiès <dkm@kataplop.net>