Fix mojo nightly
Since mojo went to 4 dots that seems to break semantic
versioning:

```
ERROR: Could not find a version that satisfies the requirement mojo<1.0.0 (from versions: 0.25.6.0.dev2025090405, 0.25.6.0.dev2025090505, 0.25.6.0.dev2025090605, 0.25.6.0.dev2025090805, 0.25.6.0.dev2025090905, 0.25.6.0.dev2025091000, 0.25.6.0.dev2025091017, 0.25.6.0.dev2025091105, 0.25.6.0.dev2025091205, 0.25.6.0.dev2025091406, 0.25.6.0.dev2025091505, 0.25.6.0.dev2025091705, 0.25.6.0.dev2025091805, 0.25.6.0rc0, 0.25.6.0rc1, 0.25.6.0rc2, 0.25.6.0rc3, 0.25.7.0.dev2025091915, 0.25.7.0.dev2025092002, 0.25.7.0.dev2025092005, 0.25.7.0.dev2025092105, 0.25.7.0.dev2025092205, 0.25.7.0.dev2025092305, 0.25.7.0.dev2025092405, 0.25.7.0.dev2025092505, 0.25.7.0.dev2025092613, 0.25.7.0.dev2025092705, 0.25.7.0.dev2025092805, 0.25.7.0.dev2025092905, 0.25.7.0.dev2025100101, 0.25.7.0.dev2025100107, 0.25.7.0.dev2025100215, 0.25.7.0.dev2025100305, 0.25.7.0.dev2025100405, 0.25.7.0.dev2025100505, 0.25.7.0.dev2025100605)
```

I tried `mojo<1.0.0.0` too but that didn't work. So I am going with `mojo` here.

CC @Ahajha